apiVersion: skaffold/v3
kind: Config
build:
  local:
    push: false
    concurrency: 0
  artifacts:
    - image: watch
      docker:
        dockerfile: Dockerfile

profiles:
  - name: dev
    activation:
      - command: dev
    manifests:
      kustomize:
        paths:
          - "k8s/base"
