apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:15
      ports:
        - containerPort: 5432
          name: db-port
      volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      env:
        - name: POSTGRES_USER
          value: root
        - name: POSTGRES_PASSWORD
          value: password
      startupProbe:
        exec:
          command:
            - pg_isready
        periodSeconds: 1
        timeoutSeconds: 2
        successThreshold: 1
        failureThreshold: 30
      livenessProbe:
        exec:
          command:
            - pg_isready
        periodSeconds: 10
        timeoutSeconds: 2
        successThreshold: 1
        failureThreshold: 1
  volumes:
    - name: postgres-storage
      hostPath:
        path: /data/sandbox/skaffold-postgres
