[package]
name = "rust-tokio-postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
rustls = "0.23.25"
tokio = { version = "1.44.2", features = ["full"] }
tokio-postgres = "0.7.13"
tokio-postgres-rustls = "0.13.0"
