apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: web-service
      protocol: TCP
      port: 80
      targetPort: web-http-port
