[package]
name = "rust-tracing-leptos-log"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.6.15", features = ["csr"] }
serde_json = "1.0.133"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
