apiVersion: skaffold/v3
kind: Config

profiles:
  - name: dev
    activation:
      - command: dev
    manifests:
      kustomize:
        paths:
          - "k8s/overlays/dev"

portForward:
  - resourceType: service
    resourceName: postgres-service
    namespace: default
    port: 5432
    localPort: 5432
