apiVersion: skaffold/v3
kind: Config

build:
  local:
    push: false

profiles:
  - name: dev
    activation:
      - command: dev
    manifests:
      kustomize:
        paths:
          - "k8s/overlays/dev"
    build:
      artifacts:
        - image: db-migrate
          context: ./db
          docker:
            dockerfile: Dockerfile


portForward:
  - resourceType: service
    resourceName: postgres-service
    namespace: default
    port: 5432
    localPort: 5432
