apiVersion: skaffold/v3
kind: Config
build:
  local:
    push: false
    concurrency: 0
  artifacts:
    - image: web
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - "www/**/*"

profiles:
  - name: dev
    activation:
      - command: dev
    manifests:
      kustomize:
        paths:
          - "k8s/overlays/dev"

portForward:
  - resourceType: service
    resourceName: web-service
    namespace: default
    port: 80
    localPort: 8080
