apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  template:
    spec:
      containers:
        - name: backend
          image: dev_container
          command: ["cargo", "watch", "--", "cargo", "run", "-p", "backend"]
