apiVersion: v1
kind: Service
metadata:
  name: public-ui-service
spec:
  type: ClusterIP
  selector:
    app: public-ui
  ports:
    - name: public-ui
      protocol: TCP
      port: 4455
      targetPort: public-ui-http
