services:
  grafana-alloy:
    image: grafana/alloy:v1.7.4
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "12345:12345" # Alloy Debug UI
    volumes:
      - ./grafana-alloy/config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      # experimental needed for otelcol.exporter.debug
      - --stability.level=experimental
      - /etc/alloy/config.alloy
    depends_on:
      - grafana

  grafana-loki:
    image: grafana/loki:2.9.13
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - "3000:3000" # Grafana UI
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasources-default.yaml:/etc/grafana/provisioning/datasources/default.yaml
