### 

@sessionId = {{CREATE_SESSION.response.body.$.value.sessionId}}


### CREATE_SESSION

POST {{URL}}/session HTTP/1.1
# Some other sensible capabilities
# =================================
# Auto install, launch and reset app.
#     "appium:app": "path/to/app",
#     "appium:enforceAppInstall": true,
#     "appium:forceAppLaunch": true,
#
# Hybrid app (App that mainly uses webview for rendering. See
# <https://github.com/appium/appium-uiautomator2-driver/blob/964672389bbe9e501958202904d23a9c86414fc9/README.md#hybrid-mode>)
# Automatic allow appium to access to webview
#     "appium:autoWebview": true,
# In order to ensure webview is rendered properly in Appium, we must set the correct chromedriver
#     "appium:chromedriverExecutable": "path/to/chromedriver",

{
  "capabilities": {
    "alwaysMatch": {
      "appium:appPackage": "com.google.android.contacts",
      "appium:automationName": "UiAutomator2",
      "appium:deviceName": "Medium_Phone_API_36",
      "platformName": "Android"
    }
  }
}


### GET_BUTTON_ADD

POST {{URL}}/session/{{sessionId}}/element HTTP/1.1

{
  "using": "accessibility id",
  "value": "Create contact"
}


### 

POST {{URL}}/session/{{sessionId}}/element/{{GET_BUTTON_ADD.response.body.$.value.ELEMENT}}/click HTTP/1.1

{}


### DELETE SESSION

DELETE {{URL}}/session/{{sessionId}} HTTP/1.1
