services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready
      interval: 10s
      retries: 30
      timeout: 2s
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
