services:
  queue:
    image: rabbitmq:3.8.34-management
    ports:
      - 5672:5672 # queue
      - 15672:15672 # management console
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - intranet

volumes:
  web_volume:

networks:
  intranet:
