services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo
    healthcheck:
      test: pg_isready
      interval: 1s
      retries: 30
      timeout: 2s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical

  electric:
    image: electricsql/electric:1.0.0-beta.18
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/demo?sslmode=disable
    ports:
      - 3000:3000
    depends_on:
      - postgres

volumes:
  postgres_data:
