services:
  schemaspy:
    image: schemaspy/schemaspy:6.2.4
    network_mode: host
    volumes:
      - $PWD/output:/output
    command:
      - -t
      - ${SS_DBTYPE}
      - -db
      - ${SS_DB}
      - -host
      - ${SS_HOST}
      - -port
      - ${SS_PORT}
      - -u
      - ${SS_USER}
      - -p
      - ${SS_PASSWORD}
